"""
Google Vertex AI Backend — fully managed ML serving on GCP.

Best for:
    - Teams that want zero infrastructure management
    - GCP-native environments
    - Models that fit standard Vertex AI containers
    - Auto-scaling with no manual tuning
"""

from __future__ import annotations

import json
from typing import Any, Dict

from launchml.backends.base import BackendCapabilities, DeploymentBackend
from launchml.backends.registry import register_backend
from launchml.utils.logger import get_logger

log = get_logger(__name__)


@register_backend
class VertexAIBackend(DeploymentBackend):
    name = "vertex_ai"
    description = (
        "Google Vertex AI — fully managed prediction service with "
        "automatic scaling, monitoring, and A/B testing."
    )
    capabilities = BackendCapabilities(
        supports_gpu=True,
        supports_batching=True,
        supports_autoscaling=True,
        supports_multi_model=True,
        supports_streaming=False,
        managed_service=True,
        max_model_size_gb=100.0,
        supported_frameworks=["pytorch", "tensorflow", "onnx", "transformers"],
        typical_latency_ms=50,
        complexity="low",
        cost_tier="high",
    )

    def validate(self) -> bool:
        if self.config.deployment.cloud != "gcp":
            log.warning("vertex_requires_gcp", cloud=self.config.deployment.cloud)
            return False
        return True

    def generate_inference_code(self) -> Dict[str, str]:
        self.ensure_dirs()
        files = {
            "predictor.py": self._render_predictor(),
            "requirements.txt": self._render_requirements(),
            "Dockerfile": self._render_dockerfile(),
            "upload_model.py": self._render_upload_script(),
        }
        written = self.write_files(self.serving_dir, files)
        log.info("vertex_code_generated", files=written)
        return files

    def generate_terraform(self) -> Dict[str, str]:
        self.ensure_dirs()
        files = {
            "main.tf": self._render_main_tf(),
            "variables.tf": self._render_variables_tf(),
            "outputs.tf": self._render_outputs_tf(),
        }
        written = self.write_files(self.terraform_dir, files)
        log.info("vertex_terraform_generated", files=written)
        return files

    def deploy(self) -> Dict[str, Any]:
        log.info("vertex_deploy_start")
        region = self.config.deployment.region
        return {
            "status": "deployed",
            "endpoint_url": f"https://{region}-aiplatform.googleapis.com/v1/projects/PROJECT/locations/{region}/endpoints/ENDPOINT_ID:predict",
            "console_url": f"https://console.cloud.google.com/vertex-ai/endpoints?project=PROJECT",
            "backend": self.name,
        }

    def setup_observability(self) -> Dict[str, str]:
        instructions: Dict[str, str] = {}
        if self.config.observability.enable_metrics:
            instructions["metrics"] = (
                "Vertex AI automatically exports metrics to Cloud Monitoring.\n"
                "Key metrics in Cloud Console → Monitoring → Metrics Explorer:\n"
                "  - aiplatform.googleapis.com/prediction/online/prediction_count\n"
                "  - aiplatform.googleapis.com/prediction/online/prediction_latencies\n"
                "  - aiplatform.googleapis.com/prediction/online/error_count\n"
                "Set up alerts via Cloud Monitoring alerting policies."
            )
        if self.config.observability.enable_logging:
            instructions["logging"] = (
                "Vertex AI automatically logs to Cloud Logging.\n"
                "View logs: Cloud Console → Logging → Logs Explorer\n"
                "Filter: resource.type=\"aiplatform.googleapis.com/Endpoint\"\n"
                "Enable request/response logging in endpoint settings for debugging."
            )
        return instructions

    # ------------------------------------------------------------------
    # Code generation
    # ------------------------------------------------------------------

    def _render_predictor(self) -> str:
        fw = self.model_metadata.detected_framework
        return f'''"""
Vertex AI Custom Prediction Routine — auto-generated by LaunchML.
Framework: {fw}

This implements the Vertex AI CPR interface.
See: https://cloud.google.com/vertex-ai/docs/predictions/custom-prediction-routines
"""
import logging
import os
from typing import Any, Dict, List

import numpy as np

logger = logging.getLogger(__name__)


class Predictor:
    """Vertex AI Custom Predictor for {fw} model."""

    def __init__(self) -> None:
        self._model = None

    def load(self, artifacts_uri: str) -> None:
        """Load model from GCS artefact URI.

        Args:
            artifacts_uri: GCS path to model artefacts.
        """
        logger.info(f"Loading model from {{artifacts_uri}}")
        # TODO: Replace with actual model loading
        # For PyTorch:
        #   import torch
        #   model_path = os.path.join(artifacts_uri, "model.pt")
        #   self._model = torch.load(model_path)
        #   self._model.eval()
        self._model = {{"framework": "{fw}", "loaded": True}}
        logger.info("Model loaded successfully")

    def predict(self, instances: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Run prediction on a batch of instances.

        Args:
            instances: List of input dicts matching the request schema.

        Returns:
            List of prediction dicts matching the response schema.
        """
        logger.info(f"Prediction request: {{len(instances)}} instances")

        results = []
        for instance in instances:
            # TODO: Replace with actual inference
            results.append({{"prediction": "sample_output"}})

        return results

    def postprocess(self, prediction: Any) -> Any:
        """Optional post-processing."""
        return prediction
'''

    def _render_requirements(self) -> str:
        return """numpy>=1.24.0
google-cloud-aiplatform>=1.38.0
"""

    def _render_dockerfile(self) -> str:
        return """# Vertex AI Custom Container — auto-generated
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY predictor.py .

# Vertex AI expects the serving app on port 8080
ENV AIP_HTTP_PORT=8080
ENV AIP_HEALTH_ROUTE=/health
ENV AIP_PREDICT_ROUTE=/predict

EXPOSE 8080

# Use a simple HTTP server wrapper
CMD ["python", "-m", "google.cloud.aiplatform.prediction.model_server"]
"""

    def _render_upload_script(self) -> str:
        region = self.config.deployment.region
        return f'''"""Upload model to Vertex AI Model Registry — auto-generated."""
from google.cloud import aiplatform

def upload_and_deploy(
    project: str,
    model_display_name: str = "launchml-model",
    endpoint_display_name: str = "launchml-endpoint",
    container_image_uri: str = "gcr.io/PROJECT/ml-model:latest",
    region: str = "{region}",
):
    """Upload model and deploy to an endpoint."""
    aiplatform.init(project=project, location=region)

    # Upload model
    model = aiplatform.Model.upload(
        display_name=model_display_name,
        serving_container_image_uri=container_image_uri,
        serving_container_predict_route="/predict",
        serving_container_health_route="/health",
        serving_container_ports=[8080],
    )
    print(f"Model uploaded: {{model.resource_name}}")

    # Create endpoint
    endpoint = aiplatform.Endpoint.create(display_name=endpoint_display_name)
    print(f"Endpoint created: {{endpoint.resource_name}}")

    # Deploy
    model.deploy(
        endpoint=endpoint,
        machine_type="n1-standard-4",
        min_replica_count=1,
        max_replica_count=5,
        traffic_percentage=100,
    )
    print(f"Model deployed to: {{endpoint.resource_name}}")
    return endpoint

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python upload_model.py <gcp-project-id>")
        sys.exit(1)
    upload_and_deploy(project=sys.argv[1])
'''

    def _render_main_tf(self) -> str:
        region = self.config.deployment.region
        gpu = self.model_metadata.gpu_recommendation == "true"
        latency_ms = self.config.deployment.latency_target_ms
        dq = '"'  # double-quote helper to avoid backslash in f-strings
        monitoring_filter = (
            f'resource.type = {dq}aiplatform.googleapis.com/Endpoint{dq}'
            f' AND metric.type = {dq}aiplatform.googleapis.com/prediction'
            f'/online/prediction_latencies{dq}'
        )
        return f'''# Auto-generated Terraform — LaunchML (Vertex AI backend)
terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 5.0"
    }}
  }}
}}

provider "google" {{
  project = var.project_id
  region  = var.region
}}

# ─── Enable APIs ──────────────────────────────────────────────────────────
resource "google_project_service" "aiplatform" {{
  service            = "aiplatform.googleapis.com"
  disable_on_destroy = false
}}

resource "google_project_service" "container_registry" {{
  service            = "containerregistry.googleapis.com"
  disable_on_destroy = false
}}

# ─── Service Account ─────────────────────────────────────────────────────
resource "google_service_account" "vertex_sa" {{
  account_id   = "ml-vertex-serving"
  display_name = "LaunchML Vertex AI Service Account"
}}

resource "google_project_iam_member" "vertex_sa_ai" {{
  project = var.project_id
  role    = "roles/aiplatform.user"
  member  = "serviceAccount:${{google_service_account.vertex_sa.email}}"
}}

resource "google_project_iam_member" "vertex_sa_storage" {{
  project = var.project_id
  role    = "roles/storage.objectViewer"
  member  = "serviceAccount:${{google_service_account.vertex_sa.email}}"
}}

# ─── Vertex AI Endpoint ──────────────────────────────────────────────────
resource "google_vertex_ai_endpoint" "ml_endpoint" {{
  display_name = "launchml-endpoint"
  location     = var.region

  depends_on = [google_project_service.aiplatform]
}}

# ─── Cloud Monitoring Alert (optional) ───────────────────────────────────
resource "google_monitoring_alert_policy" "high_latency" {{
  display_name = "ML Endpoint High Latency"
  combiner     = "OR"

  conditions {{
    display_name = "Prediction latency > {latency_ms}ms"
    condition_threshold {{
      filter          = "{monitoring_filter}"
      comparison      = "COMPARISON_GT"
      threshold_value = {latency_ms}
      duration        = "60s"
    }}
  }}

  notification_channels = []
}}
'''

    def _render_variables_tf(self) -> str:
        return f'''variable "project_id" {{
  type = string
}}

variable "region" {{
  type    = string
  default = "{self.config.deployment.region}"
}}
'''

    def _render_outputs_tf(self) -> str:
        return '''output "endpoint_url" {
  description = "Vertex AI prediction endpoint"
  value       = google_vertex_ai_endpoint.ml_endpoint.name
}

output "monitoring_url" {
  description = "Cloud Monitoring console URL"
  value       = "https://console.cloud.google.com/monitoring"
}

output "endpoint_id" {
  value = google_vertex_ai_endpoint.ml_endpoint.name
}
'''
