"""
Seldon Core Backend — Kubernetes-native ML serving with advanced traffic management.

Best for:
    - Kubernetes-native environments
    - A/B testing and canary deployments
    - Multi-model serving with custom routing
    - Organizations already running Seldon on K8s
"""

from __future__ import annotations

import json
from typing import Any, Dict

from backends.base import BackendCapabilities, DeploymentBackend
from backends.registry import register_backend
from utils.logger import get_logger

log = get_logger(__name__)


@register_backend
class SeldonBackend(DeploymentBackend):
    name = "seldon"
    description = (
        "Seldon Core — Kubernetes-native ML serving with A/B testing, "
        "canary rollouts, and advanced traffic management."
    )
    capabilities = BackendCapabilities(
        supports_gpu=True,
        supports_batching=True,
        supports_autoscaling=True,
        supports_multi_model=True,
        supports_streaming=False,
        managed_service=False,
        max_model_size_gb=20.0,
        supported_frameworks=["pytorch", "tensorflow", "onnx", "transformers"],
        typical_latency_ms=20,
        complexity="medium",
        cost_tier="medium",
    )

    def validate(self) -> bool:
        fw = self.model_metadata.detected_framework
        if fw not in self.capabilities.supported_frameworks and fw != "unknown":
            return False
        return True

    def generate_inference_code(self) -> Dict[str, str]:
        self.ensure_dirs()
        files = {
            "Model.py": self._render_model_class(),
            "requirements.txt": self._render_requirements(),
            "seldon_deployment.yaml": self._render_seldon_yaml(),
            "Dockerfile": self._render_dockerfile(),
        }
        written = self.write_files(self.serving_dir, files)
        log.info("seldon_code_generated", files=written)
        return files

    def generate_terraform(self) -> Dict[str, str]:
        self.ensure_dirs()
        files = {
            "main.tf": self._render_main_tf(),
            "variables.tf": self._render_variables_tf(),
            "outputs.tf": self._render_outputs_tf(),
        }
        written = self.write_files(self.terraform_dir, files)
        log.info("seldon_terraform_generated", files=written)
        return files

    def deploy(self) -> Dict[str, Any]:
        log.info("seldon_deploy_start")
        return {
            "status": "deployed",
            "endpoint_url": f"https://ml-seldon-{self.config.deployment.region}.example.com/seldon/default/ml-model/api/v1.0/predictions",
            "health_url": f"https://ml-seldon-{self.config.deployment.region}.example.com/seldon/default/ml-model/api/v1.0/health/status",
            "backend": self.name,
        }

    def setup_observability(self) -> Dict[str, str]:
        instructions: Dict[str, str] = {}
        if self.config.observability.enable_metrics:
            instructions["metrics"] = (
                "Seldon Core exposes Prometheus metrics automatically.\n"
                "Install Seldon Analytics dashboard for Grafana:\n"
                "  helm install seldon-analytics seldon-charts/seldon-analytics\n"
                "Key metrics: seldon_api_executor_server_requests_seconds, "
                "seldon_api_executor_server_requests_total"
            )
        if self.config.observability.enable_logging:
            instructions["logging"] = (
                "Enable request logging in SeldonDeployment spec:\n"
                "  predictors[0].logger.mode: all\n"
                "Logs are sent to a configured Kafka/ELK endpoint."
            )
        return instructions

    # ------------------------------------------------------------------
    # Code generation
    # ------------------------------------------------------------------

    def _render_model_class(self) -> str:
        fw = self.model_metadata.detected_framework
        return f'''"""
Seldon Core Model Class — auto-generated by LaunchML.
Framework: {fw}

This class implements the Seldon Python wrapper interface.
See: https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping_docker.html
"""
import logging
from typing import Any, Dict, List, Union
import numpy as np

logger = logging.getLogger(__name__)


class Model:
    """Seldon model wrapper for {fw} model."""

    def __init__(self) -> None:
        self.model = None
        self.ready = False

    def load(self) -> None:
        """Load model artefacts. Called once at startup."""
        logger.info("Loading {fw} model...")
        # TODO: Replace with actual model loading
        # Example for PyTorch:
        #   import torch
        #   self.model = torch.load("/mnt/models/model.pt")
        #   self.model.eval()
        self.model = {{"framework": "{fw}", "loaded": True}}
        self.ready = True
        logger.info("Model loaded successfully")

    def predict(
        self,
        X: np.ndarray,
        names: List[str] | None = None,
        meta: Dict[str, Any] | None = None,
    ) -> Union[np.ndarray, Dict[str, Any]]:
        """Run inference.

        Args:
            X: Input array (batch_size, features).
            names: Feature names.
            meta: Request metadata.

        Returns:
            Prediction array or dict.
        """
        logger.info(f"Prediction request: shape={{X.shape}}")

        # TODO: Replace with actual inference
        result = np.zeros((X.shape[0], 1))

        return result

    def health_status(self) -> Dict[str, Any]:
        return {{"status": "healthy", "ready": self.ready}}
'''

    def _render_requirements(self) -> str:
        return """numpy>=1.24.0
seldon-core>=1.17.0
"""

    def _render_seldon_yaml(self) -> str:
        gpu = self.model_metadata.gpu_recommendation == "true"
        return f'''# Seldon Deployment manifest — auto-generated by LaunchML
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: ml-model
  namespace: default
spec:
  predictors:
    - name: default
      replicas: {self.config.deployment.expected_rps // 50 + 1}
      graph:
        name: model
        implementation: SKLEARN_SERVER  # or CUSTOM for Python wrapper
        modelUri: "gs://your-bucket/model"
        envSecretRefName: seldon-init-container-secret
        children: []
      componentSpecs:
        - spec:
            containers:
              - name: model
                image: "your-registry/ml-model:latest"
                resources:
                  requests:
                    cpu: "1"
                    memory: "2Gi"
                    {"nvidia.com/gpu: '1'" if gpu else ""}
                  limits:
                    cpu: "2"
                    memory: "4Gi"
                    {"nvidia.com/gpu: '1'" if gpu else ""}
      traffic: 100
      {"logger:" if self.config.observability.enable_logging else ""}
      {"  mode: all" if self.config.observability.enable_logging else ""}
'''

    def _render_dockerfile(self) -> str:
        return """# Seldon Core Python Wrapper — auto-generated
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Model.py .

# Seldon expects the model class at this path
ENV MODEL_NAME=Model
ENV SERVICE_TYPE=MODEL

EXPOSE 5000
CMD exec seldon-core-microservice $MODEL_NAME --service-type $SERVICE_TYPE
"""

    def _render_main_tf(self) -> str:
        region = self.config.deployment.region
        return f'''# Auto-generated Terraform — LaunchML (Seldon backend)
terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 5.0"
    }}
    kubernetes = {{
      source  = "hashicorp/kubernetes"
      version = "~> 2.25"
    }}
    helm = {{
      source  = "hashicorp/helm"
      version = "~> 2.12"
    }}
  }}
}}

provider "google" {{
  project = var.project_id
  region  = var.region
}}

# ─── GKE Cluster ─────────────────────────────────────────────────────────
resource "google_container_cluster" "seldon_cluster" {{
  name     = "ml-seldon-cluster"
  location = var.region

  initial_node_count = var.node_count
  deletion_protection = false

  node_config {{
    machine_type = var.machine_type
    oauth_scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }}
}}

# ─── Seldon Core Helm Release ────────────────────────────────────────────
resource "helm_release" "seldon_core" {{
  name       = "seldon-core"
  repository = "https://storage.googleapis.com/seldon-charts"
  chart      = "seldon-core-operator"
  namespace  = "seldon-system"
  create_namespace = true

  set {{
    name  = "usageMetrics.enabled"
    value = "true"
  }}

  set {{
    name  = "istio.enabled"
    value = "false"
  }}

  depends_on = [google_container_cluster.seldon_cluster]
}}
'''

    def _render_variables_tf(self) -> str:
        return f'''variable "project_id" {{
  type = string
}}

variable "region" {{
  type    = string
  default = "{self.config.deployment.region}"
}}

variable "machine_type" {{
  type    = string
  default = "n1-standard-4"
}}

variable "node_count" {{
  type    = number
  default = 3
}}
'''

    def _render_outputs_tf(self) -> str:
        return '''output "endpoint_url" {
  description = "Seldon prediction endpoint"
  value       = "http://${google_container_cluster.seldon_cluster.endpoint}/seldon/default/ml-model/api/v1.0/predictions"
}

output "monitoring_url" {
  description = "Prometheus metrics URL"
  value       = "http://${google_container_cluster.seldon_cluster.endpoint}:9090"
}
'''
