"""
NVIDIA Triton Inference Server Backend.

Best for:
    - High-throughput GPU inference
    - Multi-model serving
    - Dynamic batching
    - ONNX / TensorRT / PyTorch TorchScript models
    - Production workloads requiring maximum GPU utilisation
"""

from __future__ import annotations

import json
from typing import Any, Dict

from backends.base import BackendCapabilities, DeploymentBackend
from backends.registry import register_backend
from utils.logger import get_logger

log = get_logger(__name__)


@register_backend
class TritonBackend(DeploymentBackend):
    name = "triton"
    description = (
        "NVIDIA Triton Inference Server — high-performance GPU inference "
        "with dynamic batching, multi-model, and multi-framework support."
    )
    capabilities = BackendCapabilities(
        supports_gpu=True,
        supports_batching=True,
        supports_autoscaling=True,
        supports_multi_model=True,
        supports_streaming=True,
        managed_service=False,
        max_model_size_gb=50.0,
        supported_frameworks=["pytorch", "tensorflow", "onnx", "transformers"],
        typical_latency_ms=10,
        complexity="high",
        cost_tier="medium",
    )

    def validate(self) -> bool:
        fw = self.model_metadata.detected_framework
        if fw == "unknown":
            log.warning("triton_unknown_framework")
            return False
        return True

    def generate_inference_code(self) -> Dict[str, str]:
        self.ensure_dirs()
        files = {
            "model_repository/model/config.pbtxt": self._render_triton_config(),
            "docker-compose.yaml": self._render_docker_compose(),
            "client.py": self._render_client(),
        }
        written = self.write_files(self.serving_dir, files)
        log.info("triton_code_generated", files=written)
        return files

    def generate_terraform(self) -> Dict[str, str]:
        self.ensure_dirs()
        files = {
            "main.tf": self._render_main_tf(),
            "variables.tf": self._render_variables_tf(),
            "outputs.tf": self._render_outputs_tf(),
        }
        written = self.write_files(self.terraform_dir, files)
        log.info("triton_terraform_generated", files=written)
        return files

    def deploy(self) -> Dict[str, Any]:
        log.info("triton_deploy_start")
        return {
            "status": "deployed",
            "endpoint_url": f"https://ml-triton-{self.config.deployment.region}.example.com:8000/v2/models/model/infer",
            "grpc_url": f"ml-triton-{self.config.deployment.region}.example.com:8001",
            "metrics_url": f"https://ml-triton-{self.config.deployment.region}.example.com:8002/metrics",
            "backend": self.name,
        }

    def setup_observability(self) -> Dict[str, str]:
        instructions: Dict[str, str] = {}
        if self.config.observability.enable_metrics:
            instructions["metrics"] = (
                "Triton exposes Prometheus metrics on port 8002.\n"
                "Scrape target: <host>:8002/metrics\n"
                "Key metrics: nv_inference_request_success, nv_inference_request_failure, "
                "nv_inference_queue_duration_us, nv_gpu_utilization"
            )
        if self.config.observability.enable_logging:
            instructions["logging"] = (
                "Triton logs to stdout in structured format.\n"
                "Set --log-verbose=1 for detailed request logs.\n"
                "Integrate with Cloud Logging or Fluentd."
            )
        return instructions

    # ------------------------------------------------------------------
    # Code generation
    # ------------------------------------------------------------------

    def _render_triton_config(self) -> str:
        fw = self.model_metadata.detected_framework
        platform_map = {
            "pytorch": "pytorch_libtorch",
            "tensorflow": "tensorflow_savedmodel",
            "onnx": "onnxruntime_onnx",
            "transformers": "pytorch_libtorch",
        }
        platform = platform_map.get(fw, "onnxruntime_onnx")

        return f'''# Triton Model Configuration
# Auto-generated by LaunchML

name: "model"
platform: "{platform}"

max_batch_size: 8

input [
  {{
    name: "INPUT"
    data_type: TYPE_FP32
    dims: [-1]
  }}
]

output [
  {{
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [-1]
  }}
]

dynamic_batching {{
  preferred_batch_size: [2, 4, 8]
  max_queue_delay_microseconds: 100
}}

instance_group [
  {{
    count: 1
    kind: KIND_GPU
  }}
]
'''

    def _render_docker_compose(self) -> str:
        return '''# Triton Inference Server - Docker Compose
# Auto-generated by LaunchML
version: "3.8"

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.01-py3
    ports:
      - "8000:8000"   # HTTP
      - "8001:8001"   # gRPC
      - "8002:8002"   # Metrics
    volumes:
      - ./model_repository:/models
    command: >
      tritonserver
        --model-repository=/models
        --strict-model-config=false
        --log-verbose=1
        --metrics-port=8002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
'''

    def _render_client(self) -> str:
        return '''"""Sample Triton client — auto-generated by LaunchML."""
import numpy as np

try:
    import tritonclient.http as httpclient
except ImportError:
    print("Install: pip install tritonclient[http]")
    raise

def predict(input_data: np.ndarray, url: str = "localhost:8000") -> np.ndarray:
    client = httpclient.InferenceServerClient(url=url)

    inputs = [httpclient.InferInput("INPUT", input_data.shape, "FP32")]
    inputs[0].set_data_from_numpy(input_data)

    outputs = [httpclient.InferRequestedOutput("OUTPUT")]

    result = client.infer("model", inputs=inputs, outputs=outputs)
    return result.as_numpy("OUTPUT")

if __name__ == "__main__":
    sample = np.random.randn(1, 10).astype(np.float32)
    print("Prediction:", predict(sample))
'''

    def _render_main_tf(self) -> str:
        region = self.config.deployment.region
        return f'''# Auto-generated Terraform — LaunchML (Triton backend)
terraform {{
  required_version = ">= 1.5.0"
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 5.0"
    }}
  }}
}}

provider "google" {{
  project = var.project_id
  region  = var.region
}}

# ─── GKE Cluster for Triton ──────────────────────────────────────────────
resource "google_container_cluster" "triton_cluster" {{
  name     = "ml-triton-cluster"
  location = var.region

  initial_node_count = 1
  deletion_protection = false

  node_config {{
    machine_type = var.machine_type
    oauth_scopes = ["https://www.googleapis.com/auth/cloud-platform"]

    guest_accelerator {{
      type  = var.gpu_type
      count = var.gpu_count
    }}
  }}
}}

# ─── Kubernetes namespace ─────────────────────────────────────────────────
resource "google_container_cluster" "triton_pool" {{
  name     = "ml-triton-gpu-pool"
  location = var.region

  initial_node_count = var.min_nodes
  deletion_protection = false

  node_config {{
    machine_type = var.machine_type
    guest_accelerator {{
      type  = var.gpu_type
      count = var.gpu_count
    }}
  }}

  autoscaling {{
    min_node_count = var.min_nodes
    max_node_count = var.max_nodes
  }}
}}

# ─── Load Balancer ────────────────────────────────────────────────────────
resource "google_compute_global_address" "triton_ip" {{
  name = "ml-triton-ip"
}}
'''

    def _render_variables_tf(self) -> str:
        return f'''variable "project_id" {{
  type = string
}}

variable "region" {{
  type    = string
  default = "{self.config.deployment.region}"
}}

variable "machine_type" {{
  type    = string
  default = "n1-standard-8"
}}

variable "gpu_type" {{
  type    = string
  default = "nvidia-tesla-t4"
}}

variable "gpu_count" {{
  type    = number
  default = 1
}}

variable "min_nodes" {{
  type    = number
  default = 1
}}

variable "max_nodes" {{
  type    = number
  default = 3
}}
'''

    def _render_outputs_tf(self) -> str:
        return '''output "endpoint_url" {
  description = "Triton HTTP endpoint"
  value       = "http://${google_compute_global_address.triton_ip.address}:8000"
}

output "grpc_url" {
  description = "Triton gRPC endpoint"
  value       = "${google_compute_global_address.triton_ip.address}:8001"
}

output "monitoring_url" {
  description = "Triton metrics endpoint"
  value       = "http://${google_compute_global_address.triton_ip.address}:8002/metrics"
}
'''
